### ISSUE TITLE
Moving between two lists issue

### ISSUE THREAD

**Issue by PlkMarudny** [progging/svelte-sortable#1]
Looks like that moving items between two lists is not really working, as if onMove is missing somehow? Here is the  [REPL ](https://svelte.dev/repl/2b4bb7f0fa8c468b834ce1ba3a32a641?version=3.32.3) that demonstrates that, moving form the bottom to top changes the order in the top list, moving from the top list to the bottom one leaves some _undefined_ items in the bottom list.

The code is copied to insert some debug messages.

**Comment by progging** [comment]
Thanks for the REPL! It's been a while since I worked with this repo, and I currently have my focus elsewhere. I will, however, be very happy to review and merge any pull requests that improves on this repo, if you feel so inclined.

**Comment by PlkMarudny** [comment]
Yeah, I have the enhanced version [here, ](https://svelte.dev/repl/2b4bb7f0fa8c468b834ce1ba3a32a641?version=3.32.3), uses different events, but works with multiple lists.

**Comment by PlkMarudny** [comment]
Yeah, I have the enhanced version [here, ](https://svelte.dev/repl/2b4bb7f0fa8c468b834ce1ba3a32a641?version=3.32.3), uses different events, but works with multiple lists.
